name: read_the_holy_quran
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  hexcolor: ^3.0.1
  quran: ^1.2.9
  shared_preferences: ^2.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
  # fonts:
  #   - family: QuranSurah.ttf
  #     fonts:
  #       - asset: assets/fonts/QuranSurah.ttf
